### ISSUE TITLE
Basic import of code from Tabea into repository

### ISSUE THREAD

**Issue by eileen-kuehn** [MatterMiners/lapis.caching#15]
This ticket is comprised of several sub-tasks:

* [x] import of the code from Tabeas fork
* [x] removal of everything related to LAPIS that is not relevant for caching
  * [x] Remove reference to pool (#19)
  * [x] Remove reference of job -> further removal specified in #21
  * [x] Remove reference to drone -> further removal specified in #20
